### ISSUE TITLE
Bitmap encode to gif time cost issue

### ISSUE THREAD

**Issue by AndyYoung1004** [dragon66/icafe#113]
hi
this repo is excellent and solved my issue,thanks for your great job!
I found that using the same bitmap list to encode to a gif,The first time and the second time cost is different
When I first install my apk and encode bitmap list to gif for the first time,It cost much more time than the second time
and after the first time,it turned out to cost less time when I do it again,It only happend when I first install the apk and 
the first time I encode,I do not know why

thanks!

**Comment by dragon66** [comment]
@AndyYoung1004 Not sure about this but it could be caused by install dependencies or something related.

I did find in many cases if you run multiple times continuously for the same code, it would faster after the first time and that might be caused by caching but from what you described, this is different from your case.

**Comment by AndyYoung1004** [comment]
hi dragon66:

From your describtion I am quite sure that we met the same case,Is there any way we can solve the caching issue? or do something to workaround it

thanks!

**Comment by dragon66** [comment]
@AndyYoung1004 I don't think there is a workaround for this as whatever happening here is not programmingly controlled. We don't know what is cached and when.

**Comment by dragon66** [comment]
Doesn't seems to be an issue.
