### ISSUE TITLE
Failed modify WINDOWS_XP_TITLE info

### ISSUE THREAD

**Issue by ivanooi** [dragon66/icafe#31]
Hi,

this is the code. 

JpegExif exif = new JpegExif();
      exif.addImageField(TiffTag.WINDOWS_XP_TITLE, FieldType.BYTE, "".getBytes("UTF-16LE"));

it managed to modify Windows XP comments, subject but failed on Authors and Title.
Please note that, all this fields already contained info. Ijust wanted to modify the info.

Any ideas ?
Thanks

**Comment by ivanooi** [comment]
Really hope for your help as I use this library to create an app for volunteers... big thanks

**Comment by dragon66** [comment]
@ivanooi    Can you give more details including the code works and don't work.

**Comment by dragon66** [comment]
@ivanooi For any Windows related tags, the FieldType should be FieldType.WINDOWSXP not FieldType.BYTE. Also you don't need to use "".getBytes("UTF-16LE"), just use the String itself. Refer to TestMetadata.java for more details.

**Comment by ivanooi** [comment]
Hi,

I just download the latest jar but..
it still failed making modification on that fields. THis is my test code :+1: 

      FileInputStream fin = new FileInputStream("RW_KL20151213_hyx02_012.JPG");
      FileOutputStream fout = new FileOutputStream("thumbnailAdded.jpg");      
      
//      TiffExif exif = new TiffExif();
      JpegExif exif = new JpegExif();
      
      DateFormat formatter = new SimpleDateFormat("yyyy:MM:dd HH:mm:ss");

      exif.addImageField(TiffTag.WINDOWS_XP_AUTHOR, FieldType.WINDOWSXP, "WINDOWS_XP_AUTHOR");
      exif.addImageField(TiffTag.WINDOWS_XP_TITLE, FieldType.WINDOWSXP, "Test");//.getBytes("US-ASCII")

      Metadata.insertExif(fin, fout, exif, true);
      fin.close();
      fout.close();      

 Do you need my sample photo ?

Thanks

**Comment by dragon66** [comment]
What is the error message? Can you put your sample photo somewhere?

**Comment by ivanooi** [comment]
Can I email you the photo ? 

There;s no error throw.

This are the few exceptions that I catch :+1: 

      } catch (FileNotFoundException e) {
         e.printStackTrace();
      } catch (UnsupportedEncodingException e) {
         e.printStackTrace();
      } catch (IOException e) {
         e.printStackTrace();
      }
Thanks again

**Comment by dragon66** [comment]
@ivanooi Email the photo to me.

**Comment by ivanooi** [comment]
sent. Thanks! Thanks! Thanks!

**Comment by dragon66** [comment]
I will take a look and let you know as soon as possible.

**Comment by ivanooi** [comment]
Big Thanks! :+1:  :100:  :-D 

really need your help. lot lib failed in this area. including common imaging.

**Comment by dragon66** [comment]
@ivanooi I figured out what is wrong here:

The problem:
1). The photo you provided has both EXIF and XMP and both of the them contain some of the common tags. The tags in XMP take precedence if in Windows, you right click the image->properties->details as I tested. So even if you have changed EXIF, some of the tag values will still be showing as before because they are the tag values contained in XMP. Only those tags which are in EXIF but not in XMP will be shown this way. If you view the metadata using a different tool, you will be able to see them in EXIF.
2). There are Unicode strings fields like "Artist", "Image Description" in the photo which are treated as ASCII string. Theoretically, TIFF doesn't has a field type for Unicode string. As a result, in the process of inserting EXIF, icafe took the Unicode string as ASCII and those strings become unrecognizable.

The solution:
1) If you want, you can remove XMP using icafe and keep only EXIF. After that, you can insert new EXIF tags - the same test
2. Just insert EXIF tags - some of them will be shadowed if viewed in Windows Explorer. This is not a problem if you don't care about it.

**Comment by dragon66** [comment]
@ivanooi There are two free tools which can view the EXIF metadata after you add them:
1. JPEGSnoop
2. XnViewMP

Download them and cross check the output image from icafe.

**Comment by ivanooi** [comment]
Hi, you are right! ya, some how Windows store the info in XMP! What a surprise! Look like I need to remove the XMP info.. Thanks! Thanks! Thanks!!

**Comment by ivanooi** [comment]
Hi,

Sorry, now these 2 fields failed to show up in Windows XP OS....
Windows Vista, 7 and 10 no problem. only Windows XP 
if u need the photo, let me know... 
Thanks again

![Greenshot 2019-05-21 00 42 49](https://user-images.githubusercontent.com/15061028/58113484-2dc60900-7c28-11e9-8ba2-5e7f4855f0d6.png)

**Comment by dragon66** [comment]
@ivanooi Send the photos to my email address and I will take a look.

**Comment by ivanooi** [comment]
Hi, 

Thanks for your advice. Photos sent. Basically, i had found a way to make the metadata nicely shown up in Vista, 7 and 10. No problems at all. really thanks for your help all the times.

Now only Win XP failed to display title and author...

**Comment by dragon66** [comment]
@ivanooi I can't figure out what the problem is except that the image you inserted metadata contains unicode strings and they are included in both XMP and Exif whereas the one you manually inserted metadata contains only Eixf with ASCII strings.

**Comment by ivanooi** [comment]
I had tested insert only ascii but still, nothing showed up. ..

**Comment by ivanooi** [comment]
This, only ascii for title and author..

**Comment by ivanooi** [comment]
Hi, I had managed to insert the author and title into Win XP. 
but I'm using Apache Imaging library....

![Greenshot 2019-05-24 15 19 06](https://user-images.githubusercontent.com/15061028/58309728-96370500-7e37-11e9-8857-b730f43017b6.png)

**Comment by dragon66** [comment]
@ivanooi Can you send me the image to do a comparison?

**Comment by ivanooi** [comment]
Here is the photo. I can't see any different 😌

**Comment by ivanooi** [comment]
![empty-out](https://user-images.githubusercontent.com/15061028/58328179-0f4c5180-7e64-11e9-9821-eb4b6f3759e4.jpg)

**Comment by dragon66** [comment]
@ivanooi Looks like Apache Imaging directly inserted those fields into Exif IFD instead of the Image IFD. However those are not standard Exif tags and I tried to view the information but they are not showing on my Windows 7 system.

**Comment by ivanooi** [comment]
Hi, yea... you are right... showing nothing in Win10 as well but ok with XP.

**Comment by ivanooi** [comment]
@dragon66 Hi, tested the photo you gave me. Only Author appear in Win XP 
![Greenshot 2019-05-25 08 31 14](https://user-images.githubusercontent.com/15061028/58362230-836c1100-7ec7-11e9-8e71-ce0701064fa0.png)

**Comment by dragon66** [comment]
@ivanooi That actually confirmed my guess. As for the tile is not showing, that is because the image also contains an empty Image Description which becomes the preferred title but it is empty.

Anyway, I did some changes to the code to actually include Windows related tags in ExifTag enum. Now you need to insert those windows related tags to both Image IFD and Exif IFD. This is the only way you can make it work for both Windows XP and later versions.

Check the latest changes of ICAFE and give it a try.

**Comment by ivanooi** [comment]
great! I will give it a try

**Comment by ivanooi** [comment]
Hi,

Title not working.  Author ok now

I had tried the following way :
1) adding only this 
exif.addExifField( ExifTag.WINDOWS_XP_TITLE , FieldType.WINDOWSXP

2) adding this 2 
exif.addImageField(TiffTag.WINDOWS_XP_TITLE , FieldType.WINDOWSXP
exif.addExifField( ExifTag.WINDOWS_XP_TITLE , FieldType.WINDOWSXP

3) 
exif.addImageField(TiffTag.IMAGE_DESCRIPTION  , FieldType.WINDOWSXP
exif.addImageField(TiffTag.WINDOWS_XP_TITLE , FieldType.WINDOWSXP
exif.addExifField( ExifTag.WINDOWS_XP_TITLE , FieldType.WINDOWSXP

4) 
exif.addImageField(TiffTag.WINDOWS_XP_TITLE , FieldType.WINDOWSXP
exif.addExifField( ExifTag.WINDOWS_XP_TITLE , FieldType.WINDOWSXP

exif.addImageField(TiffTag.IMAGE_DESCRIPTION  , FieldType.WINDOWSXP
exif.addImageField(TiffTag.IMAGE_DESCRIPTION  , FieldType.ASCII,

**Comment by dragon66** [comment]
@ivanooi The second way should work. Try this one:
 
![AuthorTitle](https://user-images.githubusercontent.com/7292053/58370202-b0252600-7ed1-11e9-9cc4-a3110952822f.jpg)

**Comment by ivanooi** [comment]
What had u done? I did try to spend some times looking at your code but can't find the problems at all 
Great! Finally it works! 👍 

![Greenshot 2019-05-25 22 47 12](https://user-images.githubusercontent.com/15061028/58370942-14320380-7f3f-11e9-81cd-bf7cb7d4dc75.png)

**Comment by ivanooi** [comment]
source code not yet sync back, right? cant wait to try it. thanks again

**Comment by dragon66** [comment]
@ivanooi It is in sync. I pushed the changes yesterday and used the same code to insert Title and Author in the image I provided.

**Comment by ivanooi** [comment]
I had found the problem, 

exif.addImageField(TiffTag.IMAGE_DESCRIPTION   cause the title disappear.

Thanks! 

now... I need to find a way to balance WinXP and Mac as Mac depends on TiffTag.IMAGE_DESCRIPTION

**Comment by dragon66** [comment]
@ivanooi I don't get why image description caused the title to disappear. If Windows XP read that field and take it as it's preference, it should show it. Otherwise, as you have already inserted Windows XP specific tags and it should show those tags.

When it comes to mac, it will just grab image description and works as well.

Did you add image description like this?

`exif.addImageField(TiffTag.IMAGE_DESCRIPTION , FieldType.ASCII, "Title")`

**Comment by ivanooi** [comment]
Yes, I did but it still causes WinXP title to disappear.
luckily Win7, Vista, Win10 depend on this
exif.addImageField(TiffTag.WINDOWS_XP_TITLE, FieldType.WINDOWSXP,    

so, I place the title into Exif xp subject field : 
exif.addExifField(ExifTag.WINDOWS_XP_SUBJECT , FieldType.WINDOWSXP, 

same thing, 7, vista and 10 subject fields gets it from 
exif.addImageField(TiffTag.WINDOWS_XP_SUBJECT , FieldType.WINDOWSXP,

so, in XP, u will see the subject show as "subject / title" 
but in vista, 7 and 10, subject field only show "subject" 

and I leave image_description for Mac 
exif.addImageField(TiffTag.IMAGE_DESCRIPTION , FieldType.ASCII, 
so, sacrifice XP title and make the way for Mac. anyway, u still able to see the title in the subject field in XP.

ya. bit funny but it works...
