### ISSUE TITLE
RuntimeException: XMP data size exceededs JPEG segment size

### ISSUE THREAD

**Issue by sinedsem** [dragon66/icafe#47]
Hi @dragon66! It's me again from stockhelper again =)

As usual, file : https://github.com/sinedsem/test/blob/master/7.jpg

Stack trace:

> java.lang.RuntimeException: XMP data size exceededs JPEG segment size
> 	at com.icafe4j.image.meta.jpeg.JpegXMP.write(Unknown Source)
> 	at com.icafe4j.image.jpeg.JPEGTweaker.insertXMP(Unknown Source)
> 	at com.icafe4j.image.jpeg.JPEGTweaker.insertXMP(Unknown Source)
> 	at com.icafe4j.image.meta.Metadata.insertXMP(Unknown Source)

P. S. Please find another glass of beer in your PayPal wallet =)

**Comment by dragon66** [comment]
Hi sinedsem,

Unfortunately you have hit one of the limit of icafe.

This is how it happens: for JPEG image, each metadata block could hold about 65536 bytes of data. When it comes to XMP, if the total size in bytes are within the rough limit of 65536, it will work automatically and insert that piece of data into the image. Otherwise, what should be done is the ability to split the large data trunk into separate 65536 block of the image. Adobe specification specifies that the entire XMP split into two parts: first, the normal XMP, and second, the ExtendedXMP. The first part is a normal XMP package which is able to fit into one block of the image while the second part - ExtendedXMP could be any size and later, needs to be split into smaller trunks with each of the trunk fits into one block of the image.

That said, icafe at the present stage, has no way to split the XMP data according to the specification and if it finds that the XMP data cannot be squeezed into one block of the image, it will throw an exception which is the error message you saw.

**Comment by sinedsem** [comment]
@dragon66, yes, now I see, this image already has a lot of xmp data. 

So, what should I suggest to the author of this pic? Manually clear unneccessary tags?

Are you going to fix this in future?

**Comment by dragon66** [comment]
@sinedsem Let me take a look tomorrow. If the user himself doesn't insert a very large trunk of data which exceeds the limit, there should be a way to do it.

**Comment by sinedsem** [comment]
@dragon66 I think we can use `XMPUtils.packageForJPEG()` from com.adobe.xmp.xmpcore library.
I will investigate more...

**Comment by sinedsem** [comment]
Ok, I've figured out how to work with extended xmp:

```
Map<MetadataType, Metadata> metadataMap = Metadata.readMetadata(source);

XMPMeta xmpMeta;
if (metadataMap != null && metadataMap.get(MetadataType.XMP) != null) {
	xmpMeta = XMPMetaFactory.parseFromBuffer(metadataMap.get(MetadataType.XMP).getData());
} else {
	xmpMeta = new XMPMetaImpl();
}

// edit xmpMeta

List<Metadata> values = metadataMap != null ? new ArrayList<>(metadataMap.values()) : new ArrayList<>();

StringBuilder xmp = new StringBuilder();
StringBuilder extXmp = new StringBuilder();

XMPUtils.packageForJPEG(xmpMeta, xmp, extXmp, new StringBuilder());
if (extXmp.length() > 0) {
	values.add(new JpegXMP(xmp.toString(), extXmp.toString()));
} else {
	values.add(new JpegXMP(xmp.toString()));
}
Metadata.insertMetadata(values, source, destination);
destination.close();
```

this requires com.adobe.xmp.xmpcore library:
```
<dependency>
   <groupId>com.adobe.xmp</groupId>
   <artifactId>xmpcore</artifactId>
   <version>6.1.10</version>
</dependency>
```

**Comment by dragon66** [comment]
@sinedsem I changed a bit of the JpegXMP class to auto split the XMP data into standard and extended XMP if the size is beyond the limit of one JPEG segment. Now you do without Adobe XMP core function to split the large XMP data.
